name: Scheduled Bot Run

on:
  schedule:
    # Run every 20 minutes to avoid rate limiting
    - cron: '*/20 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        cat << EOF > .env
        TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}
        TWITTER_READ_BEARER_TOKEN=${{ secrets.TWITTER_READ_BEARER_TOKEN }}
        TWITTER_READ_COOKIE=${{ secrets.TWITTER_READ_COOKIE }}
        TWITTER_READ_CSRF_TOKEN=${{ secrets.TWITTER_READ_CSRF_TOKEN }}
        TWITTER_READ_USER_AGENT=${{ secrets.TWITTER_READ_USER_AGENT }}
        TWITTER_API_URL=${{ secrets.TWITTER_API_URL }}
        TWITTER_CLIENT_ID=${{ secrets.TWITTER_CLIENT_ID }}
        TWITTER_CLIENT_SECRET=${{ secrets.TWITTER_CLIENT_SECRET }}
        TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_WRITE_BEARER_TOKEN=${{ secrets.TWITTER_WRITE_BEARER_TOKEN }}
        GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
        EOF
    
    - name: Run bot
      run: python bot.py
      timeout-minutes: 25
    
    - name: Clean up
      if: always()
      run: |
        rm -f .env
